// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrdersCustomers.Infra.Data.Context;

#nullable disable

namespace OrdersCustomers.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_alteracao");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("cliente_ativo_idx");

                    b.HasIndex("CpfCnpj")
                        .IsUnique()
                        .HasDatabaseName("cliente_cpf_cnpj_idx");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("cliente_data_criacao_idx");

                    b.HasIndex("Nome")
                        .HasDatabaseName("cliente_nome_idx");

                    b.HasIndex("Ativo", "DataCriacao")
                        .IsDescending(false, true)
                        .HasDatabaseName("cliente_ativo_data_criacao_desc_idx");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cidade");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_alteracao");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("endereco_ativo_idx");

                    b.HasIndex("Cep")
                        .HasDatabaseName("endereco_cep_idx");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasDatabaseName("endereco_cliente_id_idx");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("endereco_data_criacao_idx");

                    b.HasIndex("Ativo", "DataCriacao")
                        .IsDescending(false, true)
                        .HasDatabaseName("endereco_ativo_data_criacao_desc_idx");

                    b.ToTable("endereco", (string)null);
                });

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.ItemOrdem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_produto");

                    b.Property<Guid>("OrdemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_alteracao");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_criacao");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("itemordem_ativo_idx");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("itemordem_data_criacao_idx");

                    b.HasIndex("NomeProduto")
                        .HasDatabaseName("item_ordem_nome_produto_idx");

                    b.HasIndex("OrdemId")
                        .HasDatabaseName("item_ordem_ordem_id_idx");

                    b.HasIndex("Ativo", "DataCriacao")
                        .IsDescending(false, true)
                        .HasDatabaseName("itemordem_ativo_data_criacao_desc_idx");

                    b.ToTable("item_ordem", (string)null);
                });

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.Ordem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long>("NumeroOrdem")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_ordem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_alteracao");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_criacao");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ordem_ativo_idx");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ordem_cliente_id_idx");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("ordem_data_criacao_idx");

                    b.HasIndex("NumeroOrdem")
                        .IsUnique()
                        .HasDatabaseName("ordem_numero_ordem_idx");

                    b.HasIndex("Status")
                        .HasDatabaseName("ordem_status_idx");

                    b.HasIndex("Ativo", "DataCriacao")
                        .IsDescending(false, true)
                        .HasDatabaseName("ordem_ativo_data_criacao_desc_idx");

                    b.ToTable("ordem", (string)null);
                });

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("OrdersCustomers.Domain.Entities.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("OrdersCustomers.Domain.Entities.Endereco", "ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.ItemOrdem", b =>
                {
                    b.HasOne("OrdersCustomers.Domain.Entities.Ordem", null)
                        .WithMany("Itens")
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.Ordem", b =>
                {
                    b.HasOne("OrdersCustomers.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("OrdersCustomers.Domain.Entities.Ordem", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
